version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.0

jobs:
  build:
    working_directory: /src
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet build -c Release -o /app/build
      - run: dotnet publish -c Release -o /app/publish
      - aws-s3/copy:
          aws-access-key-id: $AWS_ACCESS_KEY_ID
          aws-region: $AWS_REGION
          aws-secret-access-key: $AWS_SECRET_ACCESS_KEY
          from: /app/publish
          to: 's3://vecd-snaplogic/test'
      - store_artifacts: 
          path: /app/publish
          destination: publish
        
workflows: 
  build-deploy:
    jobs:
      - build:
          context: builds