version: 2.1

jobs:
  build:
    working_directory: /src
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet build -c Release -o /app/build
      - run: dotnet publish -c Release -o /app/publish
        
workflows: 
  build-deploy:
    jobs:
      - build