version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.0
  sonarcloud: sonarsource/sonarcloud@1.0.2

jobs:
  build:
    working_directory: /src
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet build -c Release -o /app/build
      - run: dotnet publish -c Release -o /app/publish
      - persist_to_workspace: 
          root: /
          paths:
            - app
            - src
  
  scan:
    docker:
      - image: 'node:latest'
    steps:
      - checkout
      - sonarcloud/scan
  
  upload:
    docker:
      - image: cimg/python:3.6
    steps:
      - run: sudo apt-get update -y
      - run: sudo apt-get install -y p7zip-full
      - attach_workspace: 
          at: /tmp/workspace
      - run: 7z a kagr-portal-api.zip /tmp/workspace/app/publish/*
      - aws-s3/copy:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: kagr-portal-api.zip
          to: 's3://vecd-snaplogic/test/'

workflows: 
  build-deploy:
    jobs:
      - build
      - upload:
          requires:
            - build